version: '3.4'

services:
    db:
        image: mysql:8.0
        command: ["--default-authentication-plugin=mysql_native_password"]
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony

    php:
        image: starbugstone/todoandco-php
        build:
            context: ./
            target: app_php
        depends_on:
            - db
            - encore

    nginx:
        image: starbugstone/todoandco-nginx
        build:
            context: ./
            target: app_nginx
        ports:
            - 80:80
        depends_on:
            - php

    encore:
        image: node:13.5-alpine
        volumes:
            - ./:/app
        working_dir: /app
        command: sh -c "yarn install && yarn encore production"