<?php

use App\Entity\User;
use PHPUnit\Framework\TestCase;

class UserTest extends TestCase
{
    public function testUser()
    {
        $user = new User();
        $this->assertTrue(in_array('ROLE_USER',$user->getRoles()),"ROLE_USER in not defaulted to new user");

        $user->setUsername('HanSolo');
        $user->setEmail('hansolo@shootfirst.com');
        $this->assertEquals('HanSolo', $user->getUsername());
        $this->assertEquals('hansolo@shootfirst.com', $user->getEmail());

        //as password is generated by security, we will test that with a functional test
    }
}